#!/bin/bash
# Installs, removes or lists the launchd jobs generated by scripts/gen-launchd.js.
#   scripts/launchd.sh install     generate + copy to ~/Library/LaunchAgents + load
#   scripts/launchd.sh uninstall   unload + remove every com.ilan.cc.* and com.ilan.learninglog-sync job
#   scripts/launchd.sh status      show what launchd has loaded
# LAUNCH_AGENTS_DIR and LAUNCHCTL override the target folder and the launchctl binary (used by the tests).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${LAUNCH_AGENTS_DIR:-$HOME/Library/LaunchAgents}"
LCTL="${LAUNCHCTL:-launchctl}"
DOMAIN="gui/$(id -u)"
OUT="$ROOT/launchd/out"
mkdir -p "$ROOT/logs/launchd"

load()   { "$LCTL" bootout "$DOMAIN/$1" 2>/dev/null || true; "$LCTL" bootstrap "$DOMAIN" "${DEST:?}/${1:?}.plist"; }
unload() { "$LCTL" bootout "$DOMAIN/${1:?}" 2>/dev/null || true; }
remove() { rm -f -- "${DEST:?}/${1:?}.plist"; }
labels() { for f in "${DEST:?}"/com.ilan.cc.*.plist "${DEST:?}"/com.ilan.learninglog-sync.plist; do if [ -e "$f" ]; then basename "$f" .plist; fi; done; }

case "${1:-}" in
  install)
    # shellcheck disable=SC2086
    node "$ROOT/scripts/gen-launchd.js" --out "$OUT" ${GEN_ARGS:-}
    mkdir -p "$DEST"
    for old in $(labels); do
      if [ ! -e "$OUT/$old.plist" ]; then unload "$old"; remove "$old"; echo "removed stale $old"; fi
    done
    n=0
    for f in "$OUT"/com.ilan.*.plist; do
      label="$(basename "$f" .plist)"; cp "$f" "$DEST/"; load "$label"; n=$((n+1))
    done
    echo "installed $n jobs. Disabled agents skip themselves; enable them in the dashboard after a clean dry-run."
    echo "Logs: $ROOT/logs/launchd/   Dashboard: http://localhost:3737 (after the server job starts)"
    ;;
  uninstall)
    for label in $(labels); do unload "$label"; remove "$label"; echo "removed $label"; done
    ;;
  status)
    "$LCTL" list | grep -E 'com\.ilan\.(cc\.|learninglog-sync)' || echo "no com.ilan jobs loaded"
    ;;
  *) echo "usage: $0 install|uninstall|status" >&2; exit 2 ;;
esac
